### ISSUE TITLE
violations should be misdemeanours

### ISSUE THREAD

**Issue by novica** [discindo/semejno_nasilstvo#6]

**Comment by teofiln** [comment]
What does this entail? Changing the name of the dataset? Do we need to change translations?

**Comment by novica** [comment]
Dunno about translations. I just thought the name of the dataset should be correct.

**Comment by teofiln** [comment]
Well, deal with the translations too. No point in having a 'misdemeanors_en' where every other entry has `violation`... if that is indeed happening. Needs to be checked
